env: "local" # local, dev, prod
storage_path: "postgres://northwindman:newpassword@localhost:5432/storage?sslmode=disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s
  grace_period: 10s